baseURL = 'https://cypheru.net/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hello-friend"

[params]
defaultTheme = "dark"

[markup.goldmark.renderer]
unsafe = true

[languages]
    [languages.en]
    title = "First Cypher Union"
    subtitle = "It's a bink!"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
    logoText = "First Cypher Union"
    logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

#    [languages.en.menu]
#    [[languages.en.menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about"
#    [[languages.en.menu.main]]
#    identifier = "showcase"
#    name = "Showcase"
#    url = "/showcase"